name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          rustup component add clippy rustfmt
      - name: Check format
        run: cargo fmt -- --check
      - name: Lint by clippy
        run: cargo clippy -- -Dwarnings
      - name: Test
        run: cargo test
