name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Check format
        run: ~/.cargo/bin/cargo fmt -- --check
      # - name: Lint by clippy
      #   run: ~/.cargo/bin/cargo clippy -- -Dwarnings
      - name: what version
        run: ~/.cargo/bin/rustup show
      - name: Test
        run: ~/.cargo/bin/cargo test
